FULL_NAMES = {
    'MMF': 'Modélisation mathématique et Mathématiques Financières',
    'SDI': "Sciences des Données et de l'Information",
    'MSc DSBA': 'Master in Data Sciences \\& Business Analytics',
    'QTE': 'Quantum Engineering',
    'PSY': 'Photonic and nanosystem engineering',
    'IA': 'Intelligence Artificielle',
    'SL': 'Sciences du Logiciel',
    'ASI': 'Architecture des Systèmes Informatiques',
    'CYBER': 'Cybersécurité',
    'MSc AI': 'Master in Artificial Intelligence',
    'SRI': 'Systèmes et Réseaux Intelligents',
    'MACS': 'Systèmes communicants mobiles et autonomes',
    'OCENE': 'Objets communicants et électronique numérique embarquée',
    'NUMVI': 'Numérique et Vivant',
    'ELEN': 'Electronic Engineering',
    'ICE': 'Information and Communication Engineering',
    'RE': 'Ressources Énergétiques',
    'E2': 'Efficacité Énergétique',
    'PEG': 'Power Energy Grids',
    'SES': 'Sustainable Energy Systems',
    'HSB': 'Healthcare et Services en Biomédical',
    'ESP': 'Environnement et Production Durable',
    'CE': 'Control Engineering',
    'DS': 'Design and System Sciences',
    'SCOM': 'Supply Chain \\& Operations Management',
    'MSc ITM': 'Master in Industry Transformation Management',
    'AET': 'Aéronautique, Espace et Transports',
    'SIC': 'Sciences et Ingénieries de la Construction',
    'MDS': 'Mathématiques et Data Sciences',
    'PNT': 'Photonique et Nanotechnologies',
    'IN': 'Informatique et Numérique',
    'EN': 'Énergie',
    'VSE': 'Vivant, Santé, Environnement',
    'GSI': 'Grands Systèmes en Interaction',
    'CVT': 'Construction, Ville, Transports',
    'SCOC': 'Systèmes Communicants et Objets Connectés',
}

MENTIONS_OF_DOMINANTES = {
    'MDS': ['MMF', 'SDI', 'MSc DSBA'],
    'PNT': ['QTE', 'PSY'],
    'IN': ['IA','SL', 'ASI', 'CYBER', 'MSc AI'],
    'SCOC': ['SRI', 'MACS', 'OCENE', 'NUMVI', 'ELEN', 'ICE'],
    'EN': ['RE', 'E2', 'PEG', 'SES'], 
    'VSE': ['HSB', 'ESP'],
    'GSI': ['CE', 'DS', 'SCOM'], 
    'CVT': ['MSc ITM', 'AET', 'SIC']
}
